// import { z } from 'zod';
// import { getAiProvider } from '../providers/ai/index.js';
// import { documentStorageService } from './DocumentStorageService.js';
// import { truncateText } from '../utils/fileTypes.js';
// import { ValidationError } from '../utils/errors.js';
// import { createPptx, PptxGenJS } from '../utils/pptx.js';

// const slideSchema = z.object({
//   type: z.enum([
//     'title',
//     'objectives',
//     'content',
//     'example',
//     'diagram',
//     'summary',
//     'slo_questions',
//   ]),
//   title: z.string(),
//   bullets: z.array(z.string()).optional(),
//   notes: z.string().optional(),
// });

// const presentationSchema = z.object({
//   presentationTitle: z.string(),
//   subtitle: z.string().optional(),
//   slides: z.array(slideSchema),
// });

// export type PresentationPlan = z.infer<typeof presentationSchema>;

// export class PowerPointService {
//   async generatePlanFromDocument(
//     documentId: string,
//     userId: string,
//     options?: { subject?: string; gradeLevel?: string; sloTopics?: string[] }
//   ): Promise<PresentationPlan> {
//     const doc = await documentStorageService.getById(documentId, userId);
//     const text = await documentStorageService.getExtractedText(documentId, userId);
//     const context = truncateText(text, 80_000);

//     const sloSection = options?.sloTopics?.length
//       ? `Include SLO-based assessment questions for: ${options.sloTopics.join(', ')}.`
//       : 'Include 3-5 SLO-based assessment questions at the end.';

//     const prompt = `You are an expert teacher creating a student-friendly PowerPoint from educational material.

// Subject: ${options?.subject ?? 'General'}
// Grade level: ${options?.gradeLevel ?? 'Secondary/University'}
// Source document: ${doc.originalName}

// Create a JSON presentation plan from this document. Structure:
// 1. title slide
// 2. learning objectives slide (3-5 objectives)
// 3. multiple content slides breaking down key concepts
// 4. at least one real-life example slide
// 5. diagram slides where visuals would help (describe diagram in bullets)
// 6. summary slide
// 7. slo_questions slide with assessment questions

// ${sloSection}

// Return ONLY valid JSON matching this schema:
// {
//   "presentationTitle": "string",
//   "subtitle": "string",
//   "slides": [
//     { "type": "title|objectives|content|example|diagram|summary|slo_questions", "title": "string", "bullets": ["string"], "notes": "optional speaker notes" }
//   ]
// }

// Document content:
// ---
// ${context}
// ---`;

//     const provider = getAiProvider();
//     const response = await provider.chat({
//       messages: [{ role: 'user', content: prompt }],
//       temperature: 0.4,
//       maxTokens: 6000,
//     });

//     const json = this.extractJson(response.content);
//     const parsed = presentationSchema.safeParse(json);
//     if (!parsed.success) {
//       throw new ValidationError('AI returned invalid presentation structure', parsed.error.flatten());
//     }
//     return parsed.data;
//   }

//   async buildPptxBuffer(plan: PresentationPlan): Promise<Buffer> {
//     const pptx = createPptx();
//     pptx.author = 'Quantum AI';
//     pptx.title = plan.presentationTitle;
//     pptx.layout = 'LAYOUT_WIDE';

//     const colors = {
//       primary: '2563EB',
//       secondary: '0C4A6E',
//       accent: '60A5FA',
//       light: 'EFF6FF',
//       white: 'FFFFFF',
//     };

//     for (const slide of plan.slides) {
//       const s = pptx.addSlide();
//       s.background = { color: colors.light };

//       switch (slide.type) {
//         case 'title':
//           s.addText(plan.presentationTitle, {
//             x: 0.5,
//             y: 1.8,
//             w: 9,
//             h: 1.5,
//             fontSize: 36,
//             bold: true,
//             color: colors.secondary,
//             align: 'center',
//           });
//           if (plan.subtitle) {
//             s.addText(plan.subtitle, {
//               x: 0.5,
//               y: 3.2,
//               w: 9,
//               h: 0.8,
//               fontSize: 20,
//               color: colors.primary,
//               align: 'center',
//             });
//           }
//           s.addText('Generated by Quantum AI', {
//             x: 0.5,
//             y: 5,
//             w: 9,
//             fontSize: 12,
//             color: '64748B',
//             align: 'center',
//           });
//           break;

//         default:
//           s.addShape(PptxGenJS.ShapeType.rect, {
//             x: 0,
//             y: 0,
//             w: '100%',
//             h: 0.6,
//             fill: { color: colors.primary },
//           });
//           s.addText(slide.title, {
//             x: 0.5,
//             y: 0.1,
//             w: 9,
//             h: 0.5,
//             fontSize: 22,
//             bold: true,
//             color: colors.white,
//           });
//           if (slide.bullets?.length) {
//             s.addText(
//               slide.bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
//               {
//                 x: 0.6,
//                 y: 1,
//                 w: 8.8,
//                 h: 4.5,
//                 fontSize: slide.type === 'slo_questions' ? 16 : 18,
//                 color: colors.secondary,
//                 valign: 'top',
//               }
//             );
//           }
//           if (slide.type === 'diagram') {
//             s.addShape(PptxGenJS.ShapeType.roundRect, {
//               x: 1,
//               y: 2.5,
//               w: 8,
//               h: 2,
//               fill: { color: colors.white },
//               line: { color: colors.accent, width: 2 },
//             });
//             s.addText('Diagram area — use bullets as visual guide', {
//               x: 1.2,
//               y: 3.1,
//               w: 7.6,
//               fontSize: 14,
//               color: '64748B',
//               align: 'center',
//             });
//           }
//           if (slide.notes) {
//             s.addNotes(slide.notes);
//           }
//       }
//     }

//     const output = await pptx.write({ outputType: 'nodebuffer' });
//     return output as Buffer;
//   }

//   async generateFromDocument(
//     documentId: string,
//     userId: string,
//     options?: { subject?: string; gradeLevel?: string; sloTopics?: string[] }
//   ): Promise<{ buffer: Buffer; plan: PresentationPlan; filename: string }> {
//     const doc = await documentStorageService.getById(documentId, userId);
//     const plan = await this.generatePlanFromDocument(documentId, userId, options);
//     const buffer = await this.buildPptxBuffer(plan);
//     const base = doc.originalName.replace(/\.[^.]+$/, '');
//     return { buffer, plan, filename: `${base}-presentation.pptx` };
//   }

//   private extractJson(content: string): unknown {
//     const trimmed = content.trim();
//     const fenceMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
//     const raw = fenceMatch ? fenceMatch[1].trim() : trimmed;
//     try {
//       return JSON.parse(raw);
//     } catch {
//       const start = raw.indexOf('{');
//       const end = raw.lastIndexOf('}');
//       if (start >= 0 && end > start) {
//         return JSON.parse(raw.slice(start, end + 1));
//       }
//       throw new ValidationError('Failed to parse AI presentation JSON');
//     }
//   }
// }

// export const powerPointService = new PowerPointService();


import { z } from 'zod';
import { getAiProvider } from '../providers/ai/index.js';
import { documentStorageService } from './DocumentStorageService.js';
import { truncateText } from '../utils/fileTypes.js';
import { ValidationError } from '../utils/errors.js';
// import { createPptx, PptxGenJS } from '../utils/pptx.js';
import { createPptx } from '../utils/pptx.js';

const slideSchema = z.object({
  type: z.enum(['title', 'objectives', 'content', 'example', 'diagram', 'summary', 'slo_questions']),
  title: z.string(),
  bullets: z.array(z.string()).optional(),
  notes: z.string().optional(),
});

const THEME_IDS = [
  'science', 'math', 'history_social', 'language_arts',
  'business', 'technology', 'arts_creative', 'general',
] as const;

const presentationSchema = z.object({
  presentationTitle: z.string(),
  subtitle: z.string().optional(),
  theme: z.enum(THEME_IDS).catch('general'),
  slides: z.array(slideSchema),
});

export type PresentationPlan = z.infer<typeof presentationSchema>;

export class PowerPointService {
  async generatePlanFromDocument(
    documentId: string,
    userId: string,
    options?: { subject?: string; gradeLevel?: string; sloTopics?: string[] }
  ): Promise<PresentationPlan> {
    const doc = await documentStorageService.getById(documentId, userId);
    const text = await documentStorageService.getExtractedText(documentId, userId);
    const context = truncateText(text, 12_000);

    const sloSection = options?.sloTopics?.length
      ? `Include SLO-based assessment questions for: ${options.sloTopics.join(', ')}.`
      : 'Include 3-5 SLO-based assessment questions at the end.';

    const prompt = `You are an expert teacher creating a student-friendly PowerPoint from educational material.

Subject: ${options?.subject ?? 'General'}
Grade level: ${options?.gradeLevel ?? 'Secondary/University'}
Source document: ${doc.originalName}

Create a JSON presentation plan from this document. Structure:
1. title slide
2. learning objectives slide (3-5 objectives)
3. multiple content slides breaking down key concepts
4. at least one real-life example slide
5. diagram slides where visuals would help (describe diagram in bullets)
6. summary slide
7. slo_questions slide with assessment questions

${sloSection}

Return ONLY valid JSON matching this schema:
{
  "presentationTitle": "string",
  "subtitle": "string",
  "slides": [
    { "type": "title|objectives|content|example|diagram|summary|slo_questions", "title": "string", "bullets": ["string"], "notes": "optional speaker notes" }
  ]
}

Document content:
---
${context}
---`;

    const provider = getAiProvider();
    const response = await provider.chat({
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.4,
      maxTokens: 3000,
      responseFormat: { type: 'json_object' },
    });

    const json = this.extractJson(response.content);
    const parsed = presentationSchema.safeParse(json);
    if (!parsed.success) {
      throw new ValidationError('AI returned invalid presentation structure', parsed.error.flatten());
    }
    return parsed.data;
  }

    async buildPptxBuffer(plan: PresentationPlan): Promise<Buffer> {
    const pptx = createPptx();
    pptx.author = 'Quantum AI';
    pptx.title = plan.presentationTitle;
    pptx.layout = 'LAYOUT_WIDE';

    const colors = {
      primary: '2563EB',
      primaryDark: '1E3A8A',
      secondary: '0C4A6E',
      accent: '60A5FA',
      light: 'F8FAFC',
      white: 'FFFFFF',
      textDim: '64748B',
    };

    const typeLabels: Record<string, string> = {
      content: 'KEY POINTS',
      summary: 'SUMMARY',
      objectives: 'OBJECTIVES',
      example: 'EXAMPLE',
      diagram: 'DIAGRAM',
      slo_questions: 'DISCUSSION QUESTIONS',
    };

    plan.slides.forEach((slide, index) => {
      const s = pptx.addSlide();

      if (slide.type === 'title') {
        s.background = { color: colors.primaryDark };
        s.addShape(pptx.ShapeType.rect, {
          x: 0, y: 0, w: '100%', h: 0.12, fill: { color: colors.accent },
        });
        s.addText(plan.presentationTitle, {
          x: 0.7, y: 2.0, w: 8.6, h: 1.6,
          fontSize: 40, bold: true, color: colors.white, align: 'left',
          fontFace: 'Calibri',
        });
        if (plan.subtitle) {
          s.addText(plan.subtitle, {
            x: 0.7, y: 3.4, w: 8.6, h: 0.7,
            fontSize: 20, color: colors.accent, align: 'left', fontFace: 'Calibri',
          });
        }
        s.addText('Generated by Quantum AI', {
          x: 0.7, y: 5.2, w: 8.6, fontSize: 12, color: 'A5B4CF', align: 'left',
        });
        return;
      }

      // Every non-title slide shares the same header treatment
      s.background = { color: colors.light };
      s.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: '100%', h: 1.0, fill: { color: colors.primary },
      });
      const label = typeLabels[slide.type];
      if (label) {
        s.addText(label, {
          x: 0.5, y: 0.08, w: 9, h: 0.3,
          fontSize: 11, bold: true, color: colors.accent, charSpacing: 1,
        });
      }
      s.addText(slide.title, {
        x: 0.5, y: label ? 0.35 : 0.2, w: 9, h: 0.6,
        fontSize: 24, bold: true, color: colors.white, fontFace: 'Calibri',
      });

      if (slide.type === 'diagram') {
        s.addShape(pptx.ShapeType.roundRect, {
          x: 1, y: 1.4, w: 8, h: 3.6,
          fill: { color: colors.white },
          line: { color: colors.accent, width: 2 },
          rectRadius: 0.1,
        });
        s.addText('Diagram area — use bullets below as the visual outline', {
          x: 1.3, y: 2.9, w: 7.4, fontSize: 14, color: colors.textDim, align: 'center',
        });
        if (slide.bullets?.length) {
          s.addText(
            slide.bullets.map((b) => ({ text: b, options: { bullet: true, breakLine: true } })),
            { x: 1.3, y: 3.6, w: 7.4, h: 1.2, fontSize: 13, color: colors.secondary, valign: 'top' }
          );
        }
      } else if (slide.bullets?.length) {
        s.addText(
          slide.bullets.map((b) => ({
            text: b,
            options: { bullet: { code: '2022', indent: 20 }, breakLine: true, paraSpaceAfter: 12 },
          })),
          {
            x: 0.7, y: 1.4, w: 8.6, h: 4.3,
            fontSize: slide.type === 'slo_questions' ? 16 : 18,
            color: colors.secondary, valign: 'top', fontFace: 'Calibri',
          }
        );
      }

      s.addText(`${index + 1}`, {
        x: 9.3, y: 5.3, w: 0.5, h: 0.3, fontSize: 10, color: colors.textDim, align: 'right',
      });

      if (slide.notes) {
        s.addNotes(slide.notes);
      }
    });

    const output = await pptx.write({ outputType: 'nodebuffer' });
    return output as Buffer;
  }

  /** Generate plain text presentation format (copy-paste to PowerPoint) */
  async generatePlainText(plan: PresentationPlan): Promise<string> {
    let text = `=== ${plan.presentationTitle} ===\n`;
    if (plan.subtitle) {
      text += `${plan.subtitle}\n`;
    }
    text += `Generated by Quantum AI\n\n`;

    for (let i = 0; i < plan.slides.length; i++) {
      const slide = plan.slides[i];
      text += `--- SLIDE ${i + 1}: ${slide.title.toUpperCase()} ---\n`;
      text += `Title: ${slide.title}\n\n`;

      if (slide.bullets?.length) {
        text += `Content:\n`;
        slide.bullets.forEach((bullet) => {
          text += `  • ${bullet}\n`;
        });
      }

      if (slide.notes) {
        text += `\nNotes: ${slide.notes}\n`;
      }

      text += `\n`;
    }

    return text;
  }

  async generateFromDocument(
    documentId: string,
    userId: string,
    options?: { subject?: string; gradeLevel?: string; sloTopics?: string[] }
  ): Promise<{ buffer: Buffer; plan: PresentationPlan; filename: string }> {
    const doc = await documentStorageService.getById(documentId, userId);
    const plan = await this.generatePlanFromDocument(documentId, userId, options);
    const buffer = await this.buildPptxBuffer(plan);
    const base = doc.originalName.replace(/\.[^.]+$/, '');
    return { buffer, plan, filename: `${base}-presentation.pptx` };
  }

  private extractJson(content: string): unknown {
    const trimmed = content.trim();
    const fenceMatch = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/);
    const raw = fenceMatch ? fenceMatch[1].trim() : trimmed;
    try {
      return JSON.parse(raw);
    } catch {
      const start = raw.indexOf('{');
      const end = raw.lastIndexOf('}');
      if (start >= 0 && end > start) {
        return JSON.parse(raw.slice(start, end + 1));
      }
      throw new ValidationError('Failed to parse AI presentation JSON');
    }
  }
}

export const powerPointService = new PowerPointService();